version: "2"
services:
  base:
    image: node:10
    user: $UID
    volumes:
      - .:/app
      - .docker/node_modules:/app/node_modules
    working_dir: /app

  install:
    extends:
      service: base
    command: yarn

  server-src-build:
    extends:
      service: base
    command: yarn workspace @app/server build

  db-migrate-reset:
    extends:
      service: base
    command: yarn db:migrate reset
  db-migrate-migrate:
    extends:
      service: base
    command: yarn db:migrate migrate
