version: "2"
services:
  base:
    image: node:10
    user: $UID
    volumes:
      - .:/app
      - .docker/node_modules:/app/node_modules
      - .docker/node_modules_client:/app/@app/client/node_modules
      - .docker/node_modules_db:/app/@app/db/node_modules
      - .docker/node_modules_e2e:/app/@app/e2e/node_modules
      - .docker/node_modules_server:/app/@app/server/node_modules
      - .docker/node_modules_worker:/app/@app/worker/node_modules
    working_dir: /app

  install:
    extends:
      service: base
    command: yarn

  server-src-build:
    extends:
      service: base
    command: yarn workspace @app/server build

  db-migrate-reset:
    extends:
      service: base
    command: yarn db reset
  db-migrate-migrate:
    extends:
      service: base
    command: yarn db migrate
