version: "3"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    # Uncomment the next line to use a non-root user. On Linux, this will prevent
    # new files getting created as root, but you may need to update the USER_UID
    # and USER_GID in `Dockerfile` to match your user if not 1000.
    # user: node
    env_file:
      - docker/docker.env
    volumes:
      - .:/work
      - node_modules-volume:/work/node_modules
      # let's us run docker & docker-compose from inside container (used for yarn setup)
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /work
    depends_on:
      - db
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    ports:
      # The main server
      - "5678:5678"
      # Node `--inspect=...` port numbers for debugging
      - "9678:9678"
      - "9876:9876"
      - "9757:9757"
    depends_on:
      - db

  # This runs the database that everything else connects to
  db:
    image: postgres:11
    user: $UID
    # needs to be 2 directories deep for dump-db.sh to work
    working_dir: /root/home
    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/var/lib/postgresql/data/logs -c log_rotation_age=60 -c log_truncate_on_rotation=on -c log_filename=server_log.hour.%H%M

volumes:
  db-volume:
  node_modules-volume:
