version: "3"
services:
  dev:
    image: node:10
    user: $UID
    environment:
      - FORCE_COLOR=2
    volumes:
      - .:/work
      - .docker/node_modules:/work/node_modules
      - .docker/node_modules_client:/work/@app/client/node_modules
      - .docker/node_modules_db:/work/@app/db/node_modules
      - .docker/node_modules_e2e:/work/@app/e2e/node_modules
      - .docker/node_modules_server:/work/@app/server/node_modules
      - .docker/node_modules_worker:/work/@app/worker/node_modules
    working_dir: /work
    command: yarn dev
    ports:
      # The main server
      - 5678:5678
      # Node `--inspect=...` port numbers for debugging
      - 9678:9678
      - 9876:9876
      - 9757:9757
  pg:
    image: postgres:11
    user: $UID
    volumes:
      - .docker/postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/var/lib/postgresql/data/logs -c log_rotation_age=60 -c log_truncate_on_rotation=on -c log_filename=server_log.hour.%H%M
