name: Build and publish docker Image CI

# on:
#   push:
#     branches:
#       - master
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get short SHA
        id: env
        run: echo "::set-output name=sha::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: "Run docker server build"
        run:
          docker build -t makon/daylilycatalog:server-${{ steps.env.outputs.sha }} --file production.Dockerfile
          --build-arg TARGET=\"server\" .
      - name: "Run docker worker build"
        run:
          docker build -t makon/daylilycatalog:worker-${{ steps.env.outputs.sha }} --file production.Dockerfile
          --build-arg TARGET=\"worker\" .
      - name: "Publish server"
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: makon/daylilycatalog:server-${{ steps.env.outputs.sha }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "Publish worker"
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: makon/daylilycatalog:worker-${{ steps.env.outputs.sha }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
