name: Deploy

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set image TAG
        id: env
        run: echo "::set-output name=tag::server"
      - name: Pull new images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script_stop: true
          script: |
            echo starting...
            TAG=${{ steps.env.outputs.tag }}
            echo TAG set to $TAG
            docker system prune -f
            echo docker pruned
            cd daylilyCatalog/
            cd server/
            TAG=$TAG docker-compose pull
            echo server image pulled
            cd ../worker
            TAG=worker docker-compose pull
            echo worker image pulled
            cd ../server
            TAG=$TAG docker-compose down
            echo server stopped
            TAG=$TAG docker-compose up -d
            echo server started
            echo "$(date +%F-%T) - $TAG" >> tags.txt
            echo TAG: $TAG saved to server tags.txt
            cd ../worker
            TAG=worker docker-compose down
            echo worker stopped
            TAG=worker docker-compose up -d
            echo worker started
            echo "$(date +%F-%T) - $TAG" >> tags.txt
            echo TAG: $TAG saved to worker tags.txt
            sleep 5
            cd ../server
            echo server logs:
            TAG=$TAG docker-compose logs
            echo
            cd ../worker
            echo worker logs:
            TAG=worker docker-compose logs
            echo
            unset TAG
            echo TAG unset
            echo done
